server:
    servlet:
        context-path: /lucky
    port: 8081

limit:
    minMoney: 0.01
    maxMoney: 100
    description: 最小${limit.minMoney}元,不超过${limit.maxMoney}元


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lucky
        username: root
        password: colorful
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    mail:
      host: smtp.163.com
      username: fngqng1211@163.com
      #密码是邮箱客户端的授权码，不是网页端登陆密码
      password: 1QAZ2WSX
      #发送邮件默认的编码
      default-encoding: UTF-8

swagger:
    basePackage: com.fq.luckymoney.controller
