server:
    servlet:
        context-path: /lucky
    port: 8081

limit:
    minMoney: 0.01
    maxMoney: 100
    description: 最小${limit.minMoney}元,不超过${limit.maxMoney}元


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306?lucky
        username: root
        password: colorful
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
